BEGIN;
ALTER TABLE cms_post ALTER COLUMN date_created TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE cms_post ALTER COLUMN date_updated TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE cms_image ALTER COLUMN date_created TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE cms_image ALTER COLUMN date_updated TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE cms_page ALTER COLUMN date_created TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE cms_page ALTER COLUMN date_updated TYPE TIMESTAMP WITH TIME ZONE;
COMMIT;
